version: '3'
services:
  php_apache:
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    container_name: php_apache
    volumes:
      - .:/var/www/html
    ports:
      - "${APACHE_PORT}:${APACHE_PORT}"
    networks:
      - web_dev

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - web_dev
  
  pgsql:
    image: postgres:13
    container_name: pgsql
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "${PGSQL_PORT}:5432"
    networks:
      - web_dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}   # Email untuk login pgAdmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}   # Password untuk login pgAdmin
    ports:
      - "${PGADMIN_PORT}:80"  # Port untuk mengakses pgAdmin
    depends_on:
      - pgsql
    networks:
      - web_dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  mysql_data:
  pgsql_data:
  pgadmin_data:

networks:
  web_dev:
